### ISSUE TITLE
Feature request: Automatically create output files for each locale

### ISSUE THREAD

**Issue by icaliman** [adamduncan/eleventy-plugin-i18n#26]
Suppose we have these source files:
```
├─ src
   ├─ about.njk
   └─ index.njk
```
In these files we use the `i18n` universal filter for all texts like: `{{ 'hello' | i18n }}`

Is it possible to generate output files for each locale like bellow?
```
├─ output
   └─ en
       ├─ about.html
       └─ index.html
   └─ es
       ├─ about.html
       └─ index.html
   ├─ about.html      <--- default locale
   └─ index.html      <--- default locale
```

**Comment by shawnthompson** [comment]
I like this idea because I wouldn't have to create multiple files for each page on our site, at least not the main pages.

On the site we **have** to have all pages available in French and English. I would rather have a way to create one file and hold all the content for both languages. At least for our main landing pages that will be collections of tags that we add to our documentation pages.

What I am trying to do is put the information in the front matter for both languages and pulling it into the pages.

Using slugify for the URL with the language code. 

Not sure if this would work but I think it would be great. Eventually using Netlify / Decap CMS to allow our content owners to maintain the pages themselves. 

``` yaml
---
title:
  - en: Accessibility fundamentals
  - fr: Principes fondamentaux de l'accessibilité
layout: layouts/landing.njk
permalink: "/{{ lang }}/{{ title | slugify }}/"
description:
  - en: Discover the accessibility principles behind creating digital products and services that remove barriers for people living with disabilities while ensuring ease of use for all.
  - fr: Découvrez les principes d'accessibilité qui guident la création de produits et de services numériques qui éliminent les obstacles pour les personnes handicapées tout en assurant une facilité d'utilisation pour tous. 
keywords:
  - en:
    - Web Accessibility
    - Assistive Technology
  - fr:
    - Accessibilité du Web
    - Technologie d'assistance
---
```

Thoughts?
